#!/bin/sh
set -e
site=commercial.polyformproject.org
[ -d node_modules ] || npm ci --no-audit --no-fund
[ -n "$NO_TEST" ] || npm run test
npm run lint
npm run build
rsync -a --delete --files-from=./deployed . "$site:/var/www/$site/"
