#!/usr/bin/env node
const fs = require('fs')
const path = require('path')

const file = process.argv[2]

const input = fs.readFileSync(file, 'utf8')
fs.writeFileSync(path.basename(file, '.md') + '.json', input)
