#!/usr/bin/env node
/* npm scripts use this to convert Markdown templates to JSON files so index.js can require() them. */
const fs = require('fs')
const path = require('path')

const file = process.argv[2]

const input = fs.readFileSync(file, 'utf8')
fs.writeFileSync(path.basename(file, '.md') + '.json', JSON.stringify(input))
